	// function to grab url parameters
	function getUrlVars() {
		var vars = {};
		var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
		  vars[key] = value;
		});
		return vars;
		//usage fncChangeLoginEmailAccount(getUrlVars()["guid"]);	  		
	}//end getUrlVars
	//function to define and include required css files
	function fncRequireCssFiles1(url,dev,ver,media) {
		var link = document.createElement("link");
		link.type = "text/css";
		link.rel = "stylesheet";
		media ? link.media = media : '';
		link.href = url+"?bust=" + ((dev)? (new Date()).getTime(): ver);
		document.getElementsByTagName("head")[0].appendChild(link);
	}	// end fncRequireCssFile
	
	//function to define and include required css files
	function fncRequireJSFiles1(url,dev,ver) {
		var script  = document.createElement("script");
		script.type = "text/javascript";
		script.src = url+"?bust=" + ((dev)? (new Date()).getTime(): ver);
		document.getElementsByTagName("head")[0].appendChild(script);
	}	// end fncRequireCssFile

 	// function to sort convert date in yy-mm-dd format
	function fncDateArrange(dateObject) {
		var dateArrange;
		if(dateObject){
			var year = dateObject.split('-')[0];
			var month = dateObject.split('-')[1];
			var day = dateObject.split('-')[2];	
			dateArrange = day + "-" + month + "-" + year;
		} else {
			ateArrange = '';
		}
		return dateArrange;
		//usage fncFormateDate(date); 		
	} // end fncFormateDate
	  
	function getDepartmentListFromStorage(sTableID){	 
		if(!sessionStorage["AbsDepartmentListStorageKey"]){ 		  
		 // alert("Error");		 
		 } else {				
		intItems = JSON.parse(sessionStorage["AbsDepartmentListStorageKey"].toString());	
					
		$.fn.dataTable.ext.errMode = 'none';		
		$('#'+sTableID).on( 'error.dt', function ( e, settings, techNote, message ) { 
		console.log( 'An error has been reported by DataTables: ', message );}).dataTable(); 
		
			$('#'+sTableID).addClass('nowrap').dataTable({
						"responsive": true,			
					    "bPaginate": true,"bFilter": true,"bInfo": true,
						"data": intItems,
						"columns": [				
							{ "data": "ID",  "title": "ID"},														
							{ "data": "name",  "title": "naam" },						
							//{ "data": "companyId",  "title": "companyId" },
							//{ "data": "companyName",  "title": "companyName" },																
						],			
						"autoWidth" : true,
						"bDestroy" : true,
						stateSave: true,			
			         	// set the initial value
					   "iDisplayLength": 100,
						"dom": 'T<"clear">lfrtip',
						"tableTools": {							
						    "aButtons": [{
							    "sExtends": "pdf",
								"sButtonText": "<i class='fa fa-file-pdf-o' title='pdf'></i> PDF",
								"sTitle": "afdelingen_PDF",
								"sPdfMessage": "PDF Export",
								"sPdfSize": "letter"
							},						
							{
								"sExtends": "xls",
								"sButtonText": "<i class='fa fa-file-excel-o' title='xls'></i> EXCEL",
								"sTitle": "afdelingen_xls",
								"sPdfMessage": "xls Export",			                  
							},
							/*{
								"sExtends": "csv",
								"sButtonText": "<i class='fa fa-file-text-o' title='csv'></i> CSV",	
								"sTitle": "afdelingen_CSV",
								"sPdfMessage": "CSV Export",	                  
							},
							{
								"sExtends": "copy",
								"sButtonText": "<i class='fa fa-file' title='copy'></i>",		                  
							},
							{
								"sExtends": "print",
								"sButtonText": "<i class='fa fa-print' title='print'></i>",
								"sMessage": "Generated by Workbee <i>(press Esc to close)</i>"
							}*/],
							"sSwfPath": "https://login.workbee.eu/wb_dep/libs/datatables/swf/copy_csv_xls_pdf.swf",							
						},
						"language": {		
							"sProcessing": ((store.get("session_toLanguage") == "1") ? "Bezig..."  : "Processing..."), 
							"sLengthMenu":((store.get("session_toLanguage") == "1") ? "_MENU_ resultaten weergeven"  : "Show _MENU_ entries"), 
							"sZeroRecords": ((store.get("session_toLanguage") == "1") ? "Geen resultaten gevonden"  : "No matching records found"),
							"sInfo":  ((store.get("session_toLanguage") == "1") ? "_START_ tot _END_ van _TOTAL_ resultaten"  : "Showing _START_ to _END_ of _TOTAL_ entries"),
							"sInfoEmpty": ((store.get("session_toLanguage") == "1") ? "Geen resultaten om weer te geven" : "Showing 0 to 0 of 0 entries") ,
							"sInfoFiltered":  ((store.get("session_toLanguage") == "1") ? "(gefilterd uit _MAX_ resultaten)"  : "(filtered from _MAX_ total entries)"),
							"sInfoPostFix":((store.get("session_toLanguage") == "1") ? ""  : ""),
							"sSearch": ((store.get("session_toLanguage") == "1") ? "Zoeken:"  : "Search:"),
							"sEmptyTable":  ((store.get("session_toLanguage") == "1") ? "Geen resultaten aanwezig in de tabel"  : "No data available in table"),
							"sInfoThousands": ".",
							"sLoadingRecords": ((store.get("session_toLanguage")=="1") ? "<i class='fa fa-gear fa-1x fa-spin'></i> Een moment geduld aub - bezig met laden...":"<i class='fa fa-gear fa-1x fa-spin'></i> Loading..."),
							"oPaginate": {
							"sFirst":  ((store.get("session_toLanguage") == "1") ? "Eerste"  : "First"),
							"sLast":  ((store.get("session_toLanguage") == "1") ? "Laatste"  : "Last"),
							"sNext":  ((store.get("session_toLanguage") == "1") ? "Volgende" : "Next"),
							"sPrevious":  ((store.get("session_toLanguage") == "1") ? "Vorige"  : "Previous")						
							}
						},//end language	
					
					  });	
		
		
		
		
		 }
	}
	
	 function fncGetDepartmentData(sOrg, sUser, sPass, sId){	
		$.support.cors = true;	
		var soapBody =
			[ '<?xml version="1.0" encoding="utf-8"?>'
			,  "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ser=\"http://www.login.absentiemanager.nl/service2\">"
			,  "<soapenv:Header/>"
			,   '<soapenv:Body>'
			,     '<ser:GetDepartmentList>'
			,       '<ser:login>'
			,         '<ser:Organization>'+sOrg+'</ser:Organization>'
			,         '<ser:Username>'+sUser+'</ser:Username>'
			,         '<ser:Password>'+sPass+'</ser:Password>'			
			,       '</ser:login>'
			,       '<ser:filter>'+sId+'</ser:filter>'							
			,     '</ser:GetDepartmentList>'
			,   '</soapenv:Body>'
			, '</soapenv:Envelope>'
			].join('');		
	
		 $.ajax({  
			type: "POST",
			url: restURL+"AMS.Service2.cls",	
			async: false,	
			cache: false,			
			data: soapBody,			
			contentType: 'text/xml; charset=utf-8',
			headers: {		
				SOAPAction: 'http://www.login.absentiemanager.nl/service2/AMS.Service2.GetDepartmentList'
		   },
			success: function(result, status, req){  							
				if(status == "success") { 
				    var sData = $.xml2json(result).Body.GetDepartmentListResponse.GetDepartmentListResult.departments;							
					if($.xml2json(result).Body.GetDepartmentListResponse.GetDepartmentListResult.errorSpecified == 'true'){
					  alert("Error");
					} else {	
					//console.log(sData.Title);					
								
				  }																			
				} else {  // ERROR?  				
					
				} 				  
			  }  //success
			});    
			// -- End AJAX Call --
			return false;
	  }
